name: Attendance Logger Bot

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run attendance script
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          USER_LOGIN: ${{ github.event.comment.user.login }}
          CREATED_AT: ${{ github.event.comment.created_at }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python scripts/my_script.py
      
        # post comment after login, logout
      - name: Get formatted date
        id: get_timestamp
        run: echo "final_date=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add test/attendance.md
          git commit -m "Added attendance for ${{ steps.get_timestamp.outputs.final_date }}" || echo "No changes to commit"
          git push
          git pull origin master
